/*
 * generated by Xtext 2.12.0
 */
package edu.uhdts.dsl.functions.ide


/**
 * Use this class to register ide components.
 */
class FunctionsLanguageIdeModule extends AbstractFunctionsLanguageIdeModule {
}
