/*
 * generated by Xtext 2.12.0
 */
package edu.uhdts.dsl.functions.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class FunctionsLanguageProposalProvider extends AbstractFunctionsLanguageProposalProvider {
}
