/*
 * generated by Xtext 2.12.0
 */
package edu.uhdts.dsl.functions


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FunctionsLanguageStandaloneSetup extends FunctionsLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new FunctionsLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
