/*
 * generated by Xtext 2.12.0
 */
package edu.uhdts.dsl.functions.tests

import com.google.inject.Inject
import edu.uhdts.dsl.functions.functionsLanguage.FunctionsFile
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(FunctionsLanguageInjectorProvider)
class FunctionsLanguageParsingTest {
	@Inject
	ParseHelper<FunctionsFile> parseHelper
	
	@Test
	def void loadModel() {
	}
}
